version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
volumes:
  data: